name: "Mutation test"
on:
  workflow_dispatch:
    inputs:
      break-at:
        type: string
        description: "Configure break_at stryker option"
        default: "0"
      pr-number:
        description: "PR to run analysis on"
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: "Run mutation tests"
      uses: tom171296/run-stryker-net@feature/convet-to-ps
      with:
        testProject: "Minor.Nijn.Test/"
        breakAt: ${{ github.event.inputs.break-at }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        prNumber: ${{ github.event.inputs.pr-number }}

    - uses: actions/upload-artifact@v3
      with:
        name: html-report
        path: ${{github.workspace}}/Minor.Nijn.Test/StrykerOutput/**/**/*.html
    - uses: actions/upload-artifact@v3
      with:
        name: json-report
        path: ${{github.workspace}}/Minor.Nijn.Test/StrykerOutput/**/**/*.json