name: "Stryker.NET"
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: "Execute Stryker"
      id: stryker
      uses: tom171296/test-action-hacktober@main
      with:
        testProject: "Minor.Nijn.Test/"
    - uses: actions/upload-artifact@v3
      with:
        name: html-report
        path: ${{github.workspace}}/Minor.Nijn.Test/StrykerOutput/**/**/*.html