name: "Stryker.NET"
on:
  workflow_dispatch:
    inputs:
      break-at:
        type: string
        description: "Configure break_at stryker option"
        default: "0"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: "Execute Stryker"
      id: stryker
      uses: tom171296/run-stryker-net@main
      with:
        testProject: "Minor.Nijn.Test/"
        breakAt: ${{ github.event.inputs.break-at }}
    - uses: actions/upload-artifact@v3
      with:
        name: html-report
        path: ${{github.workspace}}/Minor.Nijn.Test/StrykerOutput/**/**/*.html