name: "Hello world"
on:
  workflow_dispatch: # Run every friday at 23:00
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: tom171296/test-action-hacktober@main
      with:
        pathToCsproj: "Piet"